### ISSUE TITLE
[BUG] SAS: Fileshares not working

### ISSUE THREAD

**Issue by ckocyigit** [sebagomez/azurestorageexplorer#122]
Hello,

when connected via SAS Token (or rather the whole Connection string, since only SAS does not work) the fileshares are displayed incorrectly.

E.g. if the File share is named banana and the fileshare has 5 differently named folders, clicking on FS Banana results in all folders within also being named "banana". Proceeding to click on a incorrectly named folder results in an error.

![image](https://github.com/sebagomez/azurestorageexplorer/assets/60385015/1334e077-357c-4ae6-991e-9d993fdaa92c)

I also can see why this happens. Analysing it via Web Tools shows that the URL is incorrectly build:

https://*****.file.core.windows.net/banana?sv=<SAS TOKEN>/banana-files (With banana files being the correct folder name)

The foldername is attached to the end but it should have been after the fileshare name:

https://*****.file.core.windows.net/banana/banana-files?sv=<SAS TOKEN>

**Comment by sebagomez** [comment]
thanks for the report @ckocyigit 
I'll take a loog

**Comment by ckocyigit** [comment]
https://github.com/sebagomez/azurestorageexplorer/pull/123
