### ISSUE TITLE
Container Volume/Overlay filled up with 100gb temp files

### ISSUE THREAD

**Issue by ckocyigit** [sebagomez/azurestorageexplorer#125]
I've been use the explorer for a while now but the monitoring just triggered an alarm due to a filled up space.

The container volume which was attached to this container contained 96 GB of *.tmp files 
![image](https://github.com/sebagomez/azurestorageexplorer/assets/60385015/c3d6300d-5a09-41ed-a471-5f82c4bcfdc5)

I had to delete those files manually in order to make the other containers work again since those were suffocating on non-available disk-space.

**Comment by sebagomez** [comment]
oh intersting... what version are you using @ckocyigit ?

I'll take a look

**Comment by ckocyigit** [comment]
v 2.13.6
