### ISSUE TITLE
Blobs not listed correctly whenm having multiple folders

### ISSUE THREAD

**Issue by razvangoga** [sebagomez/azurestorageexplorer#153]
I'm trying to use the storage explorer docker version together with the [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage) emulator.

I'm connecting to a container that has a deeper folder structure (3 4 levels deep)

On the first load, the folders under the root are displayed correctly, but on the second level (after i click on one of them) it loads nothing. If i click on "go back up on level" (back to root) it loads again nothing.

I think this has something with how the CurrentPath is set here : https://github.com/sebagomez/azurestorageexplorer/blob/cd49bad614aed2fde824461ce5cd1bd793dd882e/src/web/Pages/Blobs.razor.cs#L108 (on the first pass it's empty and the root loads and renders correctly)

**Comment by sebagomez** [comment]
Thanks for the report, I'll take a look
