### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by bhaidar** [sebagomez/azurestorageexplorer#17]
Hello,
How to login to this app?

What's the Azure Account?

**Comment by sebagomez** [comment]
On the Azure portal this credentials are called Account name and key

![awse](https://user-images.githubusercontent.com/1637983/43793709-b7b2ea56-9a52-11e8-8c91-7e50d7707906.png)

**Comment by bhaidar** [comment]
For some reason, I am not able to login!
