### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by NicoCG** [sebagomez/azurestorageexplorer#18]
Thank you for this amazing application.

Could you please provide more screenshots of Blob section, containers and files.

**Comment by sebagomez** [comment]
sure, there you go 

![image](https://user-images.githubusercontent.com/1637983/46161452-f4d1c200-c25b-11e8-80cc-933191f0abf7.png)

![image](https://user-images.githubusercontent.com/1637983/46161501-18950800-c25c-11e8-86d3-ea9ee60f3de2.png)

**Comment by NicoCG** [comment]
@sebagomez Thank you
