### ISSUE TITLE
Unable to Upload word file of 44 MB size

### ISSUE THREAD

**Issue by Sitaram2011** [sebagomez/azurestorageexplorer#20]
is there a limit for uploading files using Web Azure Storage Explorer

**Comment by sebagomez** [comment]
I'll give it a try and let you know

**Comment by michasacuer** [comment]
@sebagomez any updates on that?

**Comment by sebagomez** [comment]
Sorry, not really, but I'll try to look into that this week

**Comment by michasacuer** [comment]
@sebagomez if you will tell me how to run debugger in your solution i can look on my own as well and create PR to this repo if you wish

**Comment by sebagomez** [comment]
@michasacuer it should be as simple as running the solution in visual studio. In vscode is also possible. But I'll look into it this week and will come back with an estimate of work needed

**Comment by michasacuer** [comment]
When i put large file into form, i get NullReferenceException, `files` list is null:

![image](https://user-images.githubusercontent.com/37336963/155342166-c452b231-3fbd-486a-9e56-936f4a7763ff.png)

**Comment by sebagomez** [comment]
yes, the original problem seems to be in the client, who is not only sending the wrong data, but also not showing any error messages/ status.
I took a quick look and it seems harder than I originally thought, but will definitely take a look at it and try to fix it asap.

If you're familiar with Angular and TypeScript you can take a look [here](https://github.com/sebagomez/azurestorageexplorer/blob/5babb7145a6a17230839a98eea8f61b97cc70747/src/AzureWebStorageExplorer/ClientApp/src/app/services/utils/utils.service.ts#L84) and maybe send a PR :)

**Comment by sebagomez** [comment]
That was easy :)
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.disablerequestsizelimitattribute?view=aspnetcore-6.0

**Comment by sebagomez** [comment]
@michasacuer I didn't want to remove the limit, but I set it to 100 MBs
I hope that's good enough for you
