### ISSUE TITLE
SAS login not functional?

### ISSUE THREAD

**Issue by mikkelsandermann** [sebagomez/azurestorageexplorer#30]
Logging in with SAS tokens does not seem to work. I tried using the storage account name, container name, SAS URL, query string and different combinations of these.

**Comment by Tomer-GRTH** [comment]
Any workaround?

**Comment by mikkelsandermann** [comment]
Nope, none that I know of

**Comment by sebagomez** [comment]
work around would be using account and key, but I will take a look at it

**Comment by Tomer-GRTH** [comment]
Thanks, @sebagomez!
This can really be helpful and useful if we can use SAS tokens. Anything that I can help with?

**Comment by sebagomez** [comment]
The SAS token is working now. I have to create another issue about the app returning Internal Server error when it's actually a SAS token permission related issue
