### ISSUE TITLE
How is a shared access signature used to sign in?

### ISSUE THREAD

**Issue by jordanmills** [sebagomez/azurestorageexplorer#65]
I can sign in fine with an access key, but I can't figure out what value it wants for a SAS.  Any suggestions?

**Comment by sebagomez** [comment]
I haven't tested it in a while and I just did and there seems to be an issue with it.

Let me check it and I'll come back to you.

**Comment by sebagomez** [comment]
It's fixed now. 
Just make sure when you login you set the SaS Connection String in the key field at login. 

Also, make sure your key has read access to queues. That's a temporary limitation.

**Comment by jordanmills** [comment]
Could you share an example of what you used for the values?  I can't find any combination that seems to work.
