### ISSUE TITLE
Question: Is it possible to get the ATS record with their EDM types intact

### ISSUE THREAD

**Issue by Sandeep7OnShell** [sebagomez/azurestorageexplorer#76]
I have gone through the code and it is able to achieve what it says except few things:

It gets all the data as a string in TableEntityWrapper.Dictionary<string, object> m_properties. This creates a problem, lets's say I need to update some data on a filter condition and the types in my data do have different types from EDM. It is having a string, boolean, DateTime, etc.

Now when I update the data using this library, it changes all the types to the string which is a problem.

For creating new records also, the same issue. I can't create records with EDM type except for string.

Is it possible to achieve the same here in this package? Would love that capability.

**Comment by sebagomez** [comment]
Hey @Sandeep7OnShell it's funny you mention this today because I just faced this issue yesterday while texting other stuff.
Will definitely take a look.

**Comment by Sandeep7OnShell** [comment]
@sebagomez We are on the same page, thanks for that. Eagerly waiting for the update. :)

**Comment by Sandeep7OnShell** [comment]
@sebagomez I have been able to get the types and keep them in the dictionary till now. Not sure how can I reuse the same information while pushing the entity back into storage. Have you tried anything, any luck?

**Comment by sebagomez** [comment]
hey @Sandeep7OnShell , no sorry, I have not been able to look at it yet

**Comment by Sandeep7OnShell** [comment]
@sebagomez Any plans to check this in near future, any timeline? Could be of real use.

**Comment by sebagomez** [comment]
I do have plans, but honestly no time at the moment... we'll try to take a quick look this week

**Comment by sebagomez** [comment]
I'm gonna add this here for future reference, this seems to be the right way: https://learn.microsoft.com/en-us/rest/api/storageservices/insert-entity
